### ISSUE TITLE
enum_class_generator doesn't work in watch mode

### ISSUE THREAD

**Issue by jakemac53** [google/enum_class.dart#23]
**Note**: You will need to upgrade to version 0.3.0+6 of the build package to see these errors (watch mode was broken for the example previously)

To repro, you can just change `example/tool/build.dart` to call `watch` instead of `build`. If you make edits to `example/lib/test_enum.dart` then you will get errors like:

``` dart
[SEVERE] example|lib/test_enum.dart: Error running EnumClassGenerator for class TestEnum extends EnumClass.
Please make the following changes to use EnumClass:

1. Generated identifier "_$yes" is used multiple times in test_enum, change to something else.
2. Generated identifier "_$no" is used multiple times in test_enum, change to something else.
3. Generated identifier "_$maybe" is used multiple times in test_enum, change to something else.
4. Generated identifier "_$values" is used multiple times in test_enum, change to something else.
5. Generated identifier "_$valueOf" is used multiple times in test_enum, change to something else.
#0      EnumClassGenerator.generate.<generate_async_body> (package:enum_class_generator/enum_class_generator.dart:63:7)
#1      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#2      StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206:15)
#3      StackZoneSpecification.registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:125:48)
#4      _rootRun (dart:async/zone.dart:946)
#5      _CustomZone.run (dart:async/zone.dart:826)
#6      _CustomZone.runGuarded (dart:async/zone.dart:724)
#7      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
#8      StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206:15)
#9      StackZoneSpecification.registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:125:48)
#10     _rootRun (dart:async/zone.dart:950)
#11     _CustomZone.run (dart:async/zone.dart:826)
#12     _CustomZone.runGuarded (dart:async/zone.dart:724)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
#14     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#16     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by davidmorgan** [comment]
This works since 1.0.0.
